### ISSUE TITLE
Issues calling cli with 3 digits of serial numbers - With 5 digits it works well

### ISSUE THREAD

**Issue by hoschult** [dreadnought/energy-storage-controller#2]
Thanks for providing this tool to the community - great.

I'm using an inverter 500-90 and a PLC gateway connected with my RS485 interface (everything bought in June, 2020). But it works only if I use the last 5 digits of my serial number when calling the inverter.

Works NOT:
```
pi@xxx:~/energy-storage-controller $ ./aec-cli.py -i XXX -d /dev/ttyUSB1 --show-data
Incomplete response read
Failed to connect to inverter 467 over /dev/ttyUSB1
```

Works OK:
```
pi@xxx:~/energy-storage-controller $ ./aec-cli.py -i XXXXX -d /dev/ttyUSB1 --show-data
500-90 device, max. 510.0W, version TF0.9.25     535
PV (A): 1.35
PV (V): 63.88
PV (W): 88.69
AC (W): 80.44
```

Randomly I receive also the following error:
```
pi@xxx:~/energy-storage-controller $ ./aec-cli.py -i XXXXX -d /dev/ttyUSB1 --show-data
500-90 device, max. 510.0W, version TF0.9.25     535
get_data: invalid data
get_data: invalid data
PV (A): 1.49
PV (V): 63.62
PV (W): 93.56
AC (W): 88.21
```

**Is there a trick what I can do to get rid of these random errors?**

**Comment by dreadnought** [comment]
Hi,
regarding the inverter ID, I think that the example in the readme/help text confused you, but the description (`ID of the inverter, last 5 digits of the serial number, without leading zeros`) is actually right. My inverter ID is 00XXX, so it works when I use a three digit ID. 

I've also committed some improvements that could help with the `invalid data` messages that you see. In best case they are gone, if not you should get a more detailed error message. Please pull the latest code and test it.

**Comment by hoschult** [comment]
Ah, ok - thanks; Yes, I was confused about that - now it's clear. I have pulled the code and I'm prepared to for next sunrise ;-) Let you know.....

**Comment by hoschult** [comment]
now it looks much more reliable... I also did some improvements in cabling (RS485 usb dongle to PLC gateway) using a twisted pair and using the cable shield being connected.

in some case (I would say in one out of ten), I get the invalid date message. Seems to me that all delivered values are not in line with the expected ones:

```
500-90 device, max. 510.0W, version TF0.9.25     535
get_data: invalid data {'pv_amp': 0.84, 'pv_volt': 63.25, 'ac_watt': 13824.19, 'pv_watt': 16640.2, 'temperature': 42240.2}
```

**Comment by dreadnought** [comment]
I've added a check for the checksum of responses that we receive from the inverter. That should prevent you from receiving invalid data and would print a checksum error and retry instead.

But it's good to know that the code works with the PLC gateway at all. I've been connected only directly to the RS485 model of the inverter so far.

**Comment by hoschult** [comment]
great, thanks & already tested. What I can observe is that when I set a limit to reduce power, error happens more often. Also switched RS485 dongle to another one.... No changes. Here the output of the newest branch:

```
500-90 device, max. 510.0W, version TF0.9.25     535
Checksum wrong, 22 received vs. 75 calculated
PV (A): 0.0
PV (V): 49.22
PV (W): 0.0
AC (W): 1.36
```

**Comment by dreadnought** [comment]
Okay, but the retry mechanism works, the values that you are seeing are from a retry with a correct CRC. I've committed another change that adds the `--verbose` argument. If you don't define it, only critical error messages are shown. CRC errors can always happen on a serial connection, you shouldn't worry unless it constantly fails.

**Comment by hoschult** [comment]
great... Here is some output.

with verbose:

```
500-90 device, max. 510.0W, version TF0.9.25     535
Checksum wrong, 243 received vs. 179 calculated
1. try failed, retrying...
PV (A): 3.71
PV (V): 60.25
PV (W): 218.47
AC (W): 207.74

```

and sometimes it throws errors like this:

```
500-90 device, max. 510.0W, version TF0.9.25     535
Incomplete response read
Traceback (most recent call last):
  File "/home/pi/energy-storage-controller/aec-cli.py", line 42, in <module>
    data = inv.get_data()
  File "/home/pi/energy-storage-controller/devices/aeconversion_inverter.py", line 218, in get_data
    response_bytes = self._read_request(message, min_length=36)
  File "/home/pi/energy-storage-controller/devices/aeconversion_inverter.py", line 110, in _read_request
    min_length=min_length)
TypeError: cannot unpack non-iterable bool object
```

**Comment by dreadnought** [comment]
Thanks for testing it, e323f09 should fix the error that appeared after `Incomplete response read`.

**Comment by hoschult** [comment]
error fixed - confirmed. fyi, sporadically there is another one:

```
500-90 device, max. 510.0W, version TF0.9.25     535
Checksum wrong, 145 received vs. 203 calculated
1. try failed, retrying...
get_data: invalid length 38
get_data: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Traceback (most recent call last):
  File "/home/pi/energy-storage-controller/aec-cli.py", line 60, in <module>
    print("%s: %s" % (text, data[key]))
TypeError: 'bool' object is not subscriptable
```

If you are interested in the `get_data: xxxxxx` - Please let me know I will provide.

**Comment by dreadnought** [comment]
The exception shouldn't appear anymore and I hope that the CRC check still prevents you from getting invalid data.

What are you doing with the output, do you use it in a script?

**Comment by hoschult** [comment]
ok, great & thanks for your support. Yes, I do.... Little script with influx persistence. micro inverter acts as battery inverter in order to improve self consumption optimitation (base load scenario).

**Comment by hoschult** [comment]
one more observation from my end. If I set a limit in power production (i.e. with `--set-limit 50`), `--show status` constantly fails:

```
500-90 device, max. 510.0W, version TF0.9.25     535
Checksum wrong, 55 received vs. 119 calculated
1. try failed, retrying...
Checksum wrong, 32 received vs. 96 calculated
2. try failed, retrying...
Checksum wrong, 52 received vs. 116 calculated
3. try failed, retrying...
Checksum wrong, 60 received vs. 124 calculated
4. try failed, retrying...
Checksum wrong, 165 received vs. 229 calculated
5. try failed, retrying...
Failed after 5 tries
Errors: crc, crc, crc, crc, crc
```

However, `--show-yield` ist constantly working without errors:

```
500-90 device, max. 510.0W, version TF0.9.25     535
Watt: 44.21
Wh:   256.32
```

So there might be a timing issue when fetching bigger amount of data via RS485?

**Comment by dreadnought** [comment]
It doesn't matter how often you fetch data, it's important that only one program at a time accesses it. My service is updating the data every 10 seconds, 24/7 and it works fine. 

You might take a look at the `AEConversionInverterThread` in `/devices/aeconversion_inverter.py`. It's constantly asking the inverter for data and has a command queue, where the `set_limit` command can be added. This way only this thread is connected to the inverter and is sequentially sending commands to the inverter and processing the responses. It's also saving the data to an influxdb.
