### ISSUE TITLE
Temperature not reported correctly?

### ISSUE THREAD

**Issue by hoschult** [dreadnought/energy-storage-controller#3]
I'm running aecli for a quite long time and it works very well. However, if I want to get the reading of the inverter temperature, I alsways get 50.0:

```
pi@raspi-battery2:~ $ /home/pi/energy-storage-controller/aec-cli.py -i XXXX -d /dev/ttyUSB0 --retry 8 --output json --show-data
{"pv_amp": 0.0, "pv_volt": 56.52, "ac_watt": 0.31, "pv_watt": 5.47, "temperature": 50.0, "time": 1623930127.455973}
```

This value does not even change if I set a power limit (--set_limit 1) where I do expect that temperature should go down due to reduced utilisation. Also changing environmental temperature (from winter to summer), 50.0 remains the same.

Do you have the same issues? I use an INV350 with a powerline gateway (PLC)

**Comment by dreadnought** [comment]
That's unfortunately normal, in the official Windows software it looks like this:
![aeconversion-windows-temperature](https://user-images.githubusercontent.com/13079298/122451547-91a69180-cfa8-11eb-8bfc-7112f488e274.PNG)

As it says `<50 °C` there, my theory is that the value starts changing when the device gets really warm. But I've never watched that in reality.

Here in the screenshot of acelogger it shows only with 50°C:
https://github.com/akrypth/aeclogger

**Comment by hoschult** [comment]
ah, I see. I have to solve this topic with an external temperature sensor ;-) thanks
