### ISSUE TITLE
Which module is ment by from metrics import Metrics in smart_bms.py

### ISSUE THREAD

**Issue by bergyla** [dreadnought/energy-storage-controller#5]
In smart_bms.py an import of metrix is triggered:
from metrics import Metrics

What module must be installed for this ?

**Comment by dreadnought** [comment]
Hi, 
it gets loaded from another file in the same directory:
https://github.com/dreadnought/energy-storage-controller/blob/master/metrics.py

That then loads the InfluxDB client and sends the metrics to an InfluxDB server.

**Comment by bergyla** [comment]
Thank you. I was a little blind at that time.
